"""initdb

Revision ID: 6dbf274c9f2f
Revises: 
Create Date: 2018-08-11 15:15:04.184419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbf274c9f2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=32), nullable=True),
    sa.Column('port', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('host_user',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('host_to_host_user',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.nid'], ),
    sa.ForeignKeyConstraint(['host_user_id'], ['host_user.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_to_host_user')
    op.drop_table('host_user')
    op.drop_table('host')
    # ### end Alembic commands ###
